[package]
name = "cracker"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
md5 = "0.7.0"
password-hash = { version = "0.5.0", features = ["getrandom"] }
rand = "0.9.0"
rand_core = { version = "0.9.3", features = ["os_rng"] }
